services:
  - name: find-me-backend
    type: service
    serviceType: web
    env: node
    plan: free
    branch: main
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 4000

  - name: find-me-frontend
    type: service
    serviceType: static
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://find-me-backend.onrender.com
