services:
  - name: find-me-backend
    type: web_service
    env: node
    plan: free
    branch: main
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # You’ll add this manually in Render dashboard later
      - key: PORT
        value: 4000

  - name: find-me-frontend
    type: static_site
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://find-me-backend.onrender.com  # update to your actual backend URL after deploy
